import 'package:gridly/multitool/cable_selector/models/cable_data.dart';

class CableDataProvider {
  static final Map<CableMaterial, Map<CableType, Map<double, CableData>>>
  _data = {
    CableMaterial.cu: {
      CableType.ydy: {
        1.5: CableData(
          material: CableMaterial.cu,
          type: CableType.ydy,
          crossSection: 1.5,
          coreType: CoreType.re,
          outerDiameter: 8.5,
          heatShrinkSleeve: '12/4',
          heatShrinkLabel: '4/1.5',
        ),
        2.5: CableData(
          material: CableMaterial.cu,
          type: CableType.ydy,
          crossSection: 2.5,
          coreType: CoreType.re,
          outerDiameter: 9.5,
          heatShrinkSleeve: '15/5',
          heatShrinkLabel: '6/2',
        ),
        4.0: CableData(
          material: CableMaterial.cu,
          type: CableType.ydy,
          crossSection: 4.0,
          coreType: CoreType.re,
          outerDiameter: 11.0,
          heatShrinkSleeve: '18/6',
          heatShrinkLabel: '8/2.5',
        ),
        6.0: CableData(
          material: CableMaterial.cu,
          type: CableType.ydy,
          crossSection: 6.0,
          coreType: CoreType.re,
          outerDiameter: 12.5,
          heatShrinkSleeve: '20/7',
          heatShrinkLabel: '10/3',
        ),
        10.0: CableData(
          material: CableMaterial.cu,
          type: CableType.ydy,
          crossSection: 10.0,
          coreType: CoreType.re,
          outerDiameter: 15.0,
          heatShrinkSleeve: '25/8',
          heatShrinkLabel: '12/4',
        ),
        16.0: CableData(
          material: CableMaterial.cu,
          type: CableType.ydy,
          crossSection: 16.0,
          coreType: CoreType.re,
          outerDiameter: 18.0,
          heatShrinkSleeve: '30/10',
          heatShrinkLabel: '15/5',
        ),
        25.0: CableData(
          material: CableMaterial.cu,
          type: CableType.ydy,
          crossSection: 25.0,
          coreType: CoreType.sm,
          outerDiameter: 22.0,
          heatShrinkSleeve: '40/13',
          heatShrinkLabel: '20/6',
        ),
        35.0: CableData(
          material: CableMaterial.cu,
          type: CableType.ydy,
          crossSection: 35.0,
          coreType: CoreType.sm,
          outerDiameter: 25.0,
          heatShrinkSleeve: '45/15',
          heatShrinkLabel: '25/8',
        ),
        50.0: CableData(
          material: CableMaterial.cu,
          type: CableType.ydy,
          crossSection: 50.0,
          coreType: CoreType.sm,
          outerDiameter: 29.0,
          heatShrinkSleeve: '50/17',
          heatShrinkLabel: '25/8',
        ),
        70.0: CableData(
          material: CableMaterial.cu,
          type: CableType.ydy,
          crossSection: 70.0,
          coreType: CoreType.sm,
          outerDiameter: 34.0,
          heatShrinkSleeve: '60/20',
          heatShrinkLabel: '30/10',
        ),
        95.0: CableData(
          material: CableMaterial.cu,
          type: CableType.ydy,
          crossSection: 95.0,
          coreType: CoreType.sm,
          outerDiameter: 39.0,
          heatShrinkSleeve: '65/22',
          heatShrinkLabel: '30/10',
        ),
        120.0: CableData(
          material: CableMaterial.cu,
          type: CableType.ydy,
          crossSection: 120.0,
          coreType: CoreType.sm,
          outerDiameter: 48.0,
          heatShrinkSleeve: '75/22',
          heatShrinkLabel: '30/10',
        ),
        150.0: CableData(
          material: CableMaterial.cu,
          type: CableType.ydy,
          crossSection: 150.0,
          coreType: CoreType.sm,
          outerDiameter: 52.0,
          heatShrinkSleeve: '80/24',
          heatShrinkLabel: '40/13',
        ),
        185.0: CableData(
          material: CableMaterial.cu,
          type: CableType.ydy,
          crossSection: 185.0,
          coreType: CoreType.sm,
          outerDiameter: 57.0,
          heatShrinkSleeve: '85/25',
          heatShrinkLabel: '40/13',
        ),
        240.0: CableData(
          material: CableMaterial.cu,
          type: CableType.ydy,
          crossSection: 240.0,
          coreType: CoreType.sm,
          outerDiameter: 64.0,
          heatShrinkSleeve: '95/28',
          heatShrinkLabel: '50/15',
        ),
      },
      CableType.yky: {
        1.5: CableData(
          material: CableMaterial.cu,
          type: CableType.yky,
          crossSection: 1.5,
          coreType: CoreType.re,
          outerDiameter: 9.0,
          heatShrinkSleeve: '15/5',
          heatShrinkLabel: '4/1.5',
        ),
        2.5: CableData(
          material: CableMaterial.cu,
          type: CableType.yky,
          crossSection: 2.5,
          coreType: CoreType.re,
          outerDiameter: 10.5,
          heatShrinkSleeve: '18/6',
          heatShrinkLabel: '6/2',
        ),
        4.0: CableData(
          material: CableMaterial.cu,
          type: CableType.yky,
          crossSection: 4.0,
          coreType: CoreType.re,
          outerDiameter: 12.0,
          heatShrinkSleeve: '20/7',
          heatShrinkLabel: '8/2.5',
        ),
        6.0: CableData(
          material: CableMaterial.cu,
          type: CableType.yky,
          crossSection: 6.0,
          coreType: CoreType.re,
          outerDiameter: 13.5,
          heatShrinkSleeve: '22/8',
          heatShrinkLabel: '10/3',
        ),
        10.0: CableData(
          material: CableMaterial.cu,
          type: CableType.yky,
          crossSection: 10.0,
          coreType: CoreType.re,
          outerDiameter: 16.5,
          heatShrinkSleeve: '28/9',
          heatShrinkLabel: '12/4',
        ),
        16.0: CableData(
          material: CableMaterial.cu,
          type: CableType.yky,
          crossSection: 16.0,
          coreType: CoreType.re,
          outerDiameter: 19.5,
          heatShrinkSleeve: '32/11',
          heatShrinkLabel: '15/5',
        ),
        25.0: CableData(
          material: CableMaterial.cu,
          type: CableType.yky,
          crossSection: 25.0,
          coreType: CoreType.sm,
          outerDiameter: 23.5,
          heatShrinkSleeve: '40/13',
          heatShrinkLabel: '20/6',
        ),
        35.0: CableData(
          material: CableMaterial.cu,
          type: CableType.yky,
          crossSection: 35.0,
          coreType: CoreType.sm,
          outerDiameter: 26.5,
          heatShrinkSleeve: '45/15',
          heatShrinkLabel: '25/8',
        ),
        50.0: CableData(
          material: CableMaterial.cu,
          type: CableType.yky,
          crossSection: 50.0,
          coreType: CoreType.sm,
          outerDiameter: 31.0,
          heatShrinkSleeve: '50/17',
          heatShrinkLabel: '25/8',
        ),
        70.0: CableData(
          material: CableMaterial.cu,
          type: CableType.yky,
          crossSection: 70.0,
          coreType: CoreType.sm,
          outerDiameter: 36.0,
          heatShrinkSleeve: '60/20',
          heatShrinkLabel: '30/10',
        ),
        95.0: CableData(
          material: CableMaterial.cu,
          type: CableType.yky,
          crossSection: 95.0,
          coreType: CoreType.sm,
          outerDiameter: 41.0,
          heatShrinkSleeve: '65/22',
          heatShrinkLabel: '30/10',
        ),
        120.0: CableData(
          material: CableMaterial.cu,
          type: CableType.yky,
          crossSection: 120.0,
          coreType: CoreType.sm,
          outerDiameter: 48.0,
          heatShrinkSleeve: '75/22',
          heatShrinkLabel: '30/10',
        ),
        150.0: CableData(
          material: CableMaterial.cu,
          type: CableType.yky,
          crossSection: 150.0,
          coreType: CoreType.sm,
          outerDiameter: 52.0,
          heatShrinkSleeve: '80/24',
          heatShrinkLabel: '40/13',
        ),
        185.0: CableData(
          material: CableMaterial.cu,
          type: CableType.yky,
          crossSection: 185.0,
          coreType: CoreType.sm,
          outerDiameter: 57.0,
          heatShrinkSleeve: '85/25',
          heatShrinkLabel: '40/13',
        ),
        240.0: CableData(
          material: CableMaterial.cu,
          type: CableType.yky,
          crossSection: 240.0,
          coreType: CoreType.sm,
          outerDiameter: 64.0,
          heatShrinkSleeve: '95/28',
          heatShrinkLabel: '50/15',
        ),
      },
    },
    CableMaterial.al: {
      CableType.yaky: {
        16.0: CableData(
          material: CableMaterial.al,
          type: CableType.yaky,
          crossSection: 16.0,
          coreType: CoreType.re,
          outerDiameter: 20.0,
          heatShrinkSleeve: '32/11',
          heatShrinkLabel: '15/5',
        ),
        25.0: CableData(
          material: CableMaterial.al,
          type: CableType.yaky,
          crossSection: 25.0,
          coreType: CoreType.sm,
          outerDiameter: 24.0,
          heatShrinkSleeve: '40/13',
          heatShrinkLabel: '20/6',
        ),
        35.0: CableData(
          material: CableMaterial.al,
          type: CableType.yaky,
          crossSection: 35.0,
          coreType: CoreType.sm,
          outerDiameter: 27.5,
          heatShrinkSleeve: '45/15',
          heatShrinkLabel: '25/8',
        ),
        50.0: CableData(
          material: CableMaterial.al,
          type: CableType.yaky,
          crossSection: 50.0,
          coreType: CoreType.sm,
          outerDiameter: 32.0,
          heatShrinkSleeve: '55/18',
          heatShrinkLabel: '30/10',
        ),
        70.0: CableData(
          material: CableMaterial.al,
          type: CableType.yaky,
          crossSection: 70.0,
          coreType: CoreType.sm,
          outerDiameter: 38.0,
          heatShrinkSleeve: '60/20',
          heatShrinkLabel: '30/10',
        ),
        95.0: CableData(
          material: CableMaterial.al,
          type: CableType.yaky,
          crossSection: 95.0,
          coreType: CoreType.sm,
          outerDiameter: 44.0,
          heatShrinkSleeve: '70/22',
          heatShrinkLabel: '40/13',
        ),
        120.0: CableData(
          material: CableMaterial.al,
          type: CableType.yaky,
          crossSection: 120.0,
          coreType: CoreType.sm,
          outerDiameter: 50.0,
          heatShrinkSleeve: '75/22',
          heatShrinkLabel: '40/13',
        ),
        150.0: CableData(
          material: CableMaterial.al,
          type: CableType.yaky,
          crossSection: 150.0,
          coreType: CoreType.sm,
          outerDiameter: 55.0,
          heatShrinkSleeve: '80/24',
          heatShrinkLabel: '40/13',
        ),
        185.0: CableData(
          material: CableMaterial.al,
          type: CableType.yaky,
          crossSection: 185.0,
          coreType: CoreType.sm,
          outerDiameter: 60.0,
          heatShrinkSleeve: '85/25',
          heatShrinkLabel: '50/15',
        ),
        240.0: CableData(
          material: CableMaterial.al,
          type: CableType.yaky,
          crossSection: 240.0,
          coreType: CoreType.sm,
          outerDiameter: 62.0,
          heatShrinkSleeve: '85/25',
          heatShrinkLabel: '50/15',
        ),
      },
    },
  };

  static CableData? getCableData(
    CableMaterial material,
    CableType type,
    double crossSection,
  ) {
    return _data[material]?[type]?[crossSection];
  }

  static List<CableType> getAvailableTypes(CableMaterial material) {
    return _data[material]?.keys.toList() ?? [];
  }

  static List<double> getAvailableCrossSections(
    CableMaterial material,
    CableType type,
  ) {
    return _data[material]?[type]?.keys.toList() ?? [];
  }
}
