import 'package:gridly/multitool/symbols/models/single_line_symbol.dart';

class SingleLineSymbolsDatabase {
  static const List<SingleLineSymbol> symbols = [
    SingleLineSymbol(
      code: 'PCC',
      name: 'Punkt przyłączenia do sieci',
      description: 'Granica między siecią OSD a instalacją odbiorcy.',
      useCase: 'Schematy główne obiektu i uzgodnienia przyłączeniowe.',
      category: 'Źródła i zasilanie',
      graphicType: SingleLineGraphicType.source,
      standardRef: 'PN-HD 60364',
      keywords: ['osd', 'przyłącze', 'złącze'],
    ),
    SingleLineSymbol(
      code: 'TR',
      name: 'Transformator mocy',
      description: 'Zmiana poziomu napięcia i separacja obwodów.',
      useCase: 'Stacje SN/nn i układy zasilania technologii.',
      category: 'Źródła i zasilanie',
      graphicType: SingleLineGraphicType.transformer,
      standardRef: 'PN-EN 60617',
      keywords: ['sn', 'nn', 'trafo'],
    ),
    SingleLineSymbol(
      code: 'G',
      name: 'Agregat prądotwórczy',
      description: 'Awaryjne lub rezerwowe źródło energii.',
      useCase: 'Obiekty krytyczne, szpitale, centra danych, przemysł.',
      category: 'Źródła i zasilanie',
      graphicType: SingleLineGraphicType.source,
      standardRef: 'PN-HD 60364-5-56',
      keywords: ['generator', 'rezerwa'],
    ),
    SingleLineSymbol(
      code: 'UPS',
      name: 'Zasilacz UPS',
      description: 'Podtrzymanie bezprzerwowe dla odbiorów krytycznych.',
      useCase: 'IT, BMS, SSP, DSO, sterowanie procesem.',
      category: 'Źródła i zasilanie',
      graphicType: SingleLineGraphicType.source,
      standardRef: 'PN-EN 62040',
      keywords: ['gwarantowane', 'podtrzymanie'],
    ),
    SingleLineSymbol(
      code: 'BAT',
      name: 'Bateria akumulatorów',
      description: 'Magazyn energii dla zasilania DC/UPS.',
      useCase: 'Systemy bezpieczeństwa i automatyki.',
      category: 'Źródła i zasilanie',
      graphicType: SingleLineGraphicType.source,
      standardRef: 'PN-EN 50272',
      keywords: ['dc', 'akumulator'],
    ),
    SingleLineSymbol(
      code: 'PV',
      name: 'Generator PV',
      description: 'Źródło energii z modułów fotowoltaicznych.',
      useCase: 'Instalacje prosumenckie i przemysłowe.',
      category: 'Źródła i zasilanie',
      graphicType: SingleLineGraphicType.source,
      standardRef: 'PN-HD 60364-7-712',
      keywords: ['fotowoltaika', 'moduły'],
    ),
    SingleLineSymbol(
      code: 'INV',
      name: 'Falownik',
      description: 'Przekształtnik energoelektroniczny.',
      useCase: 'PV, napędy regulowane, układy hybrydowe.',
      category: 'Źródła i zasilanie',
      graphicType: SingleLineGraphicType.source,
      standardRef: 'PN-EN 62477',
      keywords: ['inwerter', 'przekształtnik'],
    ),
    SingleLineSymbol(
      code: 'ATS',
      name: 'Automatyczny przełącznik źródeł',
      description: 'Przełącza między źródłem podstawowym i rezerwowym.',
      useCase: 'Układy z agregatem/UPS.',
      category: 'Źródła i zasilanie',
      graphicType: SingleLineGraphicType.automation,
      standardRef: 'PN-EN 60947-6-1',
      keywords: ['samoczynne załączenie rezerwy', 'szr'],
    ),
    SingleLineSymbol(
      code: 'ESS',
      name: 'Magazyn energii (BESS)',
      description: 'System magazynowania energii z konwersją mocy.',
      useCase: 'Peak-shaving, backup, współpraca z PV.',
      category: 'Źródła i zasilanie',
      graphicType: SingleLineGraphicType.source,
      standardRef: 'PN-EN 62933',
      keywords: ['battery energy storage', 'bess'],
    ),
    SingleLineSymbol(
      code: 'CHP',
      name: 'Kogenerator CHP',
      description: 'Źródło energii elektrycznej i ciepła.',
      useCase: 'Obiekty z kogeneracją lokalną.',
      category: 'Źródła i zasilanie',
      graphicType: SingleLineGraphicType.source,
      standardRef: 'PN-EN 50465',
      keywords: ['kogeneracja'],
    ),

    SingleLineSymbol(
      code: 'RG',
      name: 'Rozdzielnica główna',
      description: 'Główny punkt dystrybucji energii w obiekcie.',
      useCase: 'Początek zasilania podrozdzielnic i odbiorów.',
      category: 'Rozdzielnice i szyny',
      graphicType: SingleLineGraphicType.board,
      standardRef: 'PN-EN 61439',
      keywords: ['main board'],
    ),
    SingleLineSymbol(
      code: 'RPOZ',
      name: 'Rozdzielnica ppoż',
      description: 'Rozdzielnica obwodów bezpieczeństwa pożarowego.',
      useCase: 'Zasilanie SSP, oddymiania, pomp pożarowych.',
      category: 'Rozdzielnice i szyny',
      graphicType: SingleLineGraphicType.board,
      standardRef: 'PN-HD 60364-5-56',
      keywords: ['pożar', 'bezpieczeństwo'],
    ),
    SingleLineSymbol(
      code: 'RP',
      name: 'Podrozdzielnica',
      description: 'Lokalny punkt rozdziału energii.',
      useCase: 'Kondygnacje, strefy technologiczne, najemcy.',
      category: 'Rozdzielnice i szyny',
      graphicType: SingleLineGraphicType.board,
      standardRef: 'PN-EN 61439',
      keywords: ['tablica', 'subboard'],
    ),
    SingleLineSymbol(
      code: 'MSB',
      name: 'Sekcja szyn zbiorczych',
      description: 'Wspólny tor prądowy w rozdzielnicy.',
      useCase: 'Pola zasilające i odpływowe o dużych prądach.',
      category: 'Rozdzielnice i szyny',
      graphicType: SingleLineGraphicType.busbar,
      standardRef: 'PN-EN 61439',
      keywords: ['busbar', 'szyny'],
    ),
    SingleLineSymbol(
      code: 'BB-CPL',
      name: 'Sprzęgło szyn',
      description: 'Łączy sekcje szyn zbiorczych.',
      useCase: 'Sekcjonowanie rozdzielnic i redundancja.',
      category: 'Rozdzielnice i szyny',
      graphicType: SingleLineGraphicType.busbar,
      standardRef: 'PN-EN 61439',
      keywords: ['sekcja', 'coupler'],
    ),
    SingleLineSymbol(
      code: 'TB',
      name: 'Listwa zaciskowa',
      description: 'Punkt przyłączeniowy i podział torów.',
      useCase: 'Połączenia wewnętrzne rozdzielnic/szaf.',
      category: 'Rozdzielnice i szyny',
      graphicType: SingleLineGraphicType.terminal,
      standardRef: 'PN-EN 60947-7',
      keywords: ['zaciski', 'terminal block'],
    ),

    SingleLineSymbol(
      code: 'Q0',
      name: 'Wyłącznik główny',
      description: 'Ręczne odłączenie całej rozdzielnicy.',
      useCase: 'Pole zasilające rozdzielnicy.',
      category: 'Aparatura łączeniowa',
      graphicType: SingleLineGraphicType.isolator,
      standardRef: 'PN-EN 60947-3',
      keywords: ['główny', 'main switch'],
    ),
    SingleLineSymbol(
      code: 'QF',
      name: 'Wyłącznik nadprądowy MCB',
      description: 'Zabezpieczenie przed przeciążeniem i zwarciem.',
      useCase: 'Odpływy obwodów końcowych.',
      category: 'Aparatura łączeniowa',
      graphicType: SingleLineGraphicType.breaker,
      standardRef: 'PN-EN 60898-1',
      keywords: ['mcb', 'es', 's-ka'],
    ),
    SingleLineSymbol(
      code: 'QFM',
      name: 'Wyłącznik mocy MCCB',
      description: 'Zabezpieczenie obwodów o większej mocy.',
      useCase: 'Pola zasilające i główne odpływy.',
      category: 'Aparatura łączeniowa',
      graphicType: SingleLineGraphicType.breaker,
      standardRef: 'PN-EN 60947-2',
      keywords: ['mccb', 'wyłącznik mocy'],
    ),
    SingleLineSymbol(
      code: 'QFD',
      name: 'Wyłącznik różnicowoprądowy RCD',
      description: 'Ochrona przy prądach upływu.',
      useCase: 'Obwody gniazd i obwody wymagające RCD.',
      category: 'Aparatura łączeniowa',
      graphicType: SingleLineGraphicType.rcd,
      standardRef: 'PN-EN 61008-1',
      keywords: ['rccb', 'różnicówka'],
    ),
    SingleLineSymbol(
      code: 'QFRC',
      name: 'Wyłącznik RCBO',
      description: 'Połączenie funkcji RCD i MCB.',
      useCase: 'Indywidualne odpływy i selektywność.',
      category: 'Aparatura łączeniowa',
      graphicType: SingleLineGraphicType.rcbo,
      standardRef: 'PN-EN 61009-1',
      keywords: ['rcbo', 'różnicowo-nadprądowy'],
    ),
    SingleLineSymbol(
      code: 'QS',
      name: 'Rozłącznik izolacyjny',
      description: 'Odłączenie bez członu zabezpieczającego.',
      useCase: 'Pola sekcyjne i rozłączanie torów.',
      category: 'Aparatura łączeniowa',
      graphicType: SingleLineGraphicType.isolator,
      standardRef: 'PN-EN 60947-3',
      keywords: ['isolator'],
    ),
    SingleLineSymbol(
      code: 'FR',
      name: 'Rozłącznik bezpiecznikowy',
      description: 'Rozłącznik z wkładkami topikowymi.',
      useCase: 'Odpływy większych mocy i ochrona selektywna.',
      category: 'Aparatura łączeniowa',
      graphicType: SingleLineGraphicType.fuse,
      standardRef: 'PN-EN 60947-3',
      keywords: ['fuse switch'],
    ),
    SingleLineSymbol(
      code: 'FU',
      name: 'Wkładka topikowa',
      description: 'Człon topikowy gG/aM.',
      useCase: 'Pola bezpiecznikowe i ochrona transformatorów/silników.',
      category: 'Aparatura łączeniowa',
      graphicType: SingleLineGraphicType.fuse,
      standardRef: 'PN-EN 60269',
      keywords: ['bezpiecznik', 'gG', 'aM'],
    ),
    SingleLineSymbol(
      code: 'KM',
      name: 'Stycznik',
      description: 'Zdalne łączenie obwodów mocy.',
      useCase: 'Sterowanie silnikami i odbiorami.',
      category: 'Aparatura łączeniowa',
      graphicType: SingleLineGraphicType.contactor,
      standardRef: 'PN-EN 60947-4-1',
      keywords: ['contactor'],
    ),
    SingleLineSymbol(
      code: 'QD',
      name: 'Rozłącznik mocy',
      description: 'Łącznik do obciążeniowego rozłączania toru.',
      useCase: 'Pola zasilające i sekcyjne nn.',
      category: 'Aparatura łączeniowa',
      graphicType: SingleLineGraphicType.isolator,
      standardRef: 'PN-EN 60947-3',
      keywords: ['load break switch'],
    ),
    SingleLineSymbol(
      code: 'ACB',
      name: 'Wyłącznik powietrzny ACB',
      description: 'Wyłącznik mocy dla wysokich prądów nn.',
      useCase: 'Rozdzielnice główne i szyny główne.',
      category: 'Aparatura łączeniowa',
      graphicType: SingleLineGraphicType.breaker,
      standardRef: 'PN-EN 60947-2',
      keywords: ['air circuit breaker'],
    ),
    SingleLineSymbol(
      code: 'SDF',
      name: 'Wyłącznik selektywny',
      description: 'Człon ochronny o nastawach selektywnych.',
      useCase: 'Koordynacja zabezpieczeń i stopniowanie zadziałania.',
      category: 'Aparatura łączeniowa',
      graphicType: SingleLineGraphicType.breaker,
      standardRef: 'PN-EN 60947-2',
      keywords: ['selektywność'],
    ),

    SingleLineSymbol(
      code: 'SPD-T1',
      name: 'Ogranicznik przepięć Typ 1',
      description: 'Odprowadza prądy udarowe piorunowe.',
      useCase: 'Główne rozdzielnice i obiekty z LPS.',
      category: 'Ochrona i ppoż',
      graphicType: SingleLineGraphicType.grounding,
      standardRef: 'PN-EN 61643-11',
      keywords: ['ochronnik', 'przepięcie'],
    ),
    SingleLineSymbol(
      code: 'SPD-T2',
      name: 'Ogranicznik przepięć Typ 2',
      description: 'Ochrona przed przepięciami łączeniowymi.',
      useCase: 'Rozdzielnice piętrowe i lokalne.',
      category: 'Ochrona i ppoż',
      graphicType: SingleLineGraphicType.grounding,
      standardRef: 'PN-EN 61643-11',
      keywords: ['ochronnik', 't2'],
    ),
    SingleLineSymbol(
      code: 'AFDD',
      name: 'Wyłącznik łukoochronny',
      description: 'Wykrywa niebezpieczne łuki elektryczne.',
      useCase: 'Obwody podwyższonego ryzyka pożaru.',
      category: 'Ochrona i ppoż',
      graphicType: SingleLineGraphicType.breaker,
      standardRef: 'PN-EN 62606',
      keywords: ['arc fault'],
    ),
    SingleLineSymbol(
      code: 'PE',
      name: 'Przewód ochronny',
      description: 'Tor ochrony przeciwporażeniowej.',
      useCase: 'Połączenia ochronne urządzeń i rozdzielnic.',
      category: 'Ochrona i ppoż',
      graphicType: SingleLineGraphicType.pe,
      standardRef: 'PN-HD 60364',
      keywords: ['uziemienie', 'ochronny'],
    ),
    SingleLineSymbol(
      code: 'PEN',
      name: 'Przewód PEN',
      description: 'Wspólny tor ochronno-neutralny.',
      useCase: 'Układy TN-C przed rozdziałem.',
      category: 'Ochrona i ppoż',
      graphicType: SingleLineGraphicType.pen,
      standardRef: 'PN-HD 60364',
      keywords: ['tn-c'],
    ),
    SingleLineSymbol(
      code: 'GSU',
      name: 'Główna szyna uziemiająca',
      description: 'Węzeł połączeń wyrównawczych.',
      useCase: 'Połączenia PE, LPS i instalacji obcych.',
      category: 'Ochrona i ppoż',
      graphicType: SingleLineGraphicType.grounding,
      standardRef: 'PN-HD 60364-5-54',
      keywords: ['ekwipotencjalizacja'],
    ),
    SingleLineSymbol(
      code: 'LPS',
      name: 'Połączenie z instalacją odgromową',
      description: 'Integracja układu ochrony odgromowej z elektryką.',
      useCase: 'Koordynacja ochrony przepięciowej.',
      category: 'Ochrona i ppoż',
      graphicType: SingleLineGraphicType.grounding,
      standardRef: 'PN-EN 62305',
      keywords: ['odgromowa', 'piorun'],
    ),
    SingleLineSymbol(
      code: 'PWP',
      name: 'Przeciwpożarowy wyłącznik prądu',
      description: 'Awaryjne odłączenie zasilania obiektu/strefy.',
      useCase: 'Obiekty wymagające uzgodnień ppoż.',
      category: 'Ochrona i ppoż',
      graphicType: SingleLineGraphicType.automation,
      standardRef: 'Warunki techniczne ppoż',
      keywords: ['ppoz', 'fire switch'],
    ),
    SingleLineSymbol(
      code: 'IMD',
      name: 'Monitor stanu izolacji',
      description: 'Nadzór rezystancji izolacji w układach IT.',
      useCase: 'Szpitale, przemysł i zasilanie ciągłe IT.',
      category: 'Ochrona i ppoż',
      graphicType: SingleLineGraphicType.automation,
      standardRef: 'PN-EN 61557-8',
      keywords: ['insulation monitor', 'it'],
    ),
    SingleLineSymbol(
      code: 'RCM',
      name: 'Monitor prądu różnicowego',
      description: 'Ciągły pomiar prądów upływu.',
      useCase: 'Predykcja awarii i utrzymanie ruchu.',
      category: 'Ochrona i ppoż',
      graphicType: SingleLineGraphicType.meter,
      standardRef: 'PN-EN 62020',
      keywords: ['residual current monitor'],
    ),
    SingleLineSymbol(
      code: 'EPO',
      name: 'Awaryjne wyłączenie zasilania',
      description: 'Emergency Power Off dla stref krytycznych.',
      useCase: 'Serwerownie, laboratoria, linie technologiczne.',
      category: 'Ochrona i ppoż',
      graphicType: SingleLineGraphicType.pushButton,
      standardRef: 'PN-EN 60204-1',
      keywords: ['emergency off'],
    ),

    SingleLineSymbol(
      code: 'kWh',
      name: 'Licznik energii',
      description: 'Pomiar energii czynnej/biernej.',
      useCase: 'Pomiary rozliczeniowe i podliczniki.',
      category: 'Pomiar i jakość energii',
      graphicType: SingleLineGraphicType.meter,
      standardRef: 'MID / PN-EN 50470',
      keywords: ['meter', 'podlicznik'],
    ),
    SingleLineSymbol(
      code: 'PQM',
      name: 'Analizator jakości energii',
      description: 'Monitoring mocy, harmonicznych i zdarzeń.',
      useCase: 'Nadzór jakości zasilania i audyty energetyczne.',
      category: 'Pomiar i jakość energii',
      graphicType: SingleLineGraphicType.meter,
      standardRef: 'PN-EN 61000-4-30',
      keywords: ['harmoniczne', 'quality'],
    ),
    SingleLineSymbol(
      code: 'CT',
      name: 'Przekładnik prądowy',
      description: 'Pomiar pośredni prądu.',
      useCase: 'Układy licznikowe i analizatory.',
      category: 'Pomiar i jakość energii',
      graphicType: SingleLineGraphicType.meter,
      standardRef: 'PN-EN 61869-2',
      keywords: ['przekładnik'],
    ),
    SingleLineSymbol(
      code: 'VT',
      name: 'Przekładnik napięciowy',
      description: 'Pomiar pośredni napięcia.',
      useCase: 'Pola pomiarowe i monitoring SN/nn.',
      category: 'Pomiar i jakość energii',
      graphicType: SingleLineGraphicType.meter,
      standardRef: 'PN-EN 61869-3',
      keywords: ['voltage transformer'],
    ),
    SingleLineSymbol(
      code: 'A',
      name: 'Amperomierz',
      description: 'Pomiar prądu w torze.',
      useCase: 'Tablice pomiarowe i pulpity.',
      category: 'Pomiar i jakość energii',
      graphicType: SingleLineGraphicType.meter,
      standardRef: 'PN-EN 60051',
      keywords: ['amper'],
    ),
    SingleLineSymbol(
      code: 'V',
      name: 'Woltomierz',
      description: 'Pomiar napięcia w torze.',
      useCase: 'Tablice pomiarowe i pola zasilające.',
      category: 'Pomiar i jakość energii',
      graphicType: SingleLineGraphicType.meter,
      standardRef: 'PN-EN 60051',
      keywords: ['voltage'],
    ),
    SingleLineSymbol(
      code: 'Hz',
      name: 'Częstotliwościomierz',
      description: 'Pomiar częstotliwości zasilania.',
      useCase: 'Monitoring źródeł i jakości energii.',
      category: 'Pomiar i jakość energii',
      graphicType: SingleLineGraphicType.meter,
      standardRef: 'PN-EN 60051',
      keywords: ['frequency'],
    ),
    SingleLineSymbol(
      code: 'cosφ',
      name: 'Miernik współczynnika mocy',
      description: 'Pomiar przesunięcia fazowego i cosφ.',
      useCase: 'Kontrola kompensacji mocy biernej.',
      category: 'Pomiar i jakość energii',
      graphicType: SingleLineGraphicType.meter,
      standardRef: 'PN-EN 62053',
      keywords: ['power factor'],
    ),
    SingleLineSymbol(
      code: 'APFC',
      name: 'Regulator kompensacji mocy biernej',
      description: 'Automatyczne sterowanie baterią kondensatorów.',
      useCase: 'Rozdzielnice z kompensacją mocy biernej.',
      category: 'Pomiar i jakość energii',
      graphicType: SingleLineGraphicType.automation,
      standardRef: 'PN-EN 61921',
      keywords: ['kompensacja', 'bateria kondensatorów'],
    ),

    SingleLineSymbol(
      code: 'M',
      name: 'Silnik trójfazowy',
      description: 'Odbiornik napędowy 3~.',
      useCase: 'Napędy pomp, wentylatorów i maszyn.',
      category: 'Odbiory i napędy',
      graphicType: SingleLineGraphicType.motor,
      standardRef: 'PN-EN 60034',
      keywords: ['motor', '3f'],
    ),
    SingleLineSymbol(
      code: 'MS',
      name: 'Wyłącznik silnikowy',
      description: 'Ręczne załączanie i ochrona silnika.',
      useCase: 'Rozdzielnice napędowe MCC.',
      category: 'Odbiory i napędy',
      graphicType: SingleLineGraphicType.motor,
      standardRef: 'PN-EN 60947-4-1',
      keywords: ['mms'],
    ),
    SingleLineSymbol(
      code: 'RT',
      name: 'Przekaźnik termiczny',
      description: 'Zabezpieczenie przeciążeniowe silników.',
      useCase: 'Układy stycznikowe DOL/rewers.',
      category: 'Odbiory i napędy',
      graphicType: SingleLineGraphicType.thermal,
      standardRef: 'PN-EN 60947-4-1',
      keywords: ['overload'],
    ),
    SingleLineSymbol(
      code: 'VFD',
      name: 'Przemiennik częstotliwości',
      description: 'Regulacja prędkości napędu.',
      useCase: 'Napędy pomp i wentylatorów o zmiennym obciążeniu.',
      category: 'Odbiory i napędy',
      graphicType: SingleLineGraphicType.source,
      standardRef: 'PN-EN 61800',
      keywords: ['falownik', 'napęd'],
    ),
    SingleLineSymbol(
      code: 'HE',
      name: 'Grzałka elektryczna',
      description: 'Odbiornik rezystancyjny.',
      useCase: 'Nagrzewnice i układy procesowe.',
      category: 'Odbiory i napędy',
      graphicType: SingleLineGraphicType.generic,
      standardRef: 'PN-HD 60364',
      keywords: ['heater'],
    ),
    SingleLineSymbol(
      code: 'PMP',
      name: 'Pompa',
      description: 'Napęd pompowy technologiczny.',
      useCase: 'Hydrofornie, ppoż, proces.',
      category: 'Odbiory i napędy',
      graphicType: SingleLineGraphicType.motor,
      standardRef: 'PN-HD 60364',
      keywords: ['pump'],
    ),
    SingleLineSymbol(
      code: 'FAN',
      name: 'Wentylator',
      description: 'Napęd układu wentylacji.',
      useCase: 'Centrale HVAC i oddymianie.',
      category: 'Odbiory i napędy',
      graphicType: SingleLineGraphicType.motor,
      standardRef: 'PN-HD 60364',
      keywords: ['fan', 'hvac'],
    ),
    SingleLineSymbol(
      code: 'PMP-FIRE',
      name: 'Pompa pożarowa',
      description: 'Odbiornik bezpieczeństwa ppoż.',
      useCase: 'Instalacje hydrantowe i tryskaczowe.',
      category: 'Odbiory i napędy',
      graphicType: SingleLineGraphicType.motor,
      standardRef: 'PN-HD 60364-5-56',
      keywords: ['fire pump', 'ppoż'],
    ),
    SingleLineSymbol(
      code: 'SMK',
      name: 'Klapa oddymiająca / siłownik',
      description: 'Element wykonawczy systemu oddymiania.',
      useCase: 'Systemy bezpieczeństwa pożarowego.',
      category: 'Odbiory i napędy',
      graphicType: SingleLineGraphicType.automation,
      standardRef: 'PN-EN 12101',
      keywords: ['oddymianie'],
    ),

    SingleLineSymbol(
      code: 'PLC',
      name: 'Sterownik PLC',
      description: 'Sterowanie logiczne procesem.',
      useCase: 'Automatyka przemysłowa i budynkowa.',
      category: 'Sterowanie i automatyka',
      graphicType: SingleLineGraphicType.automation,
      standardRef: 'PN-EN 61131',
      keywords: ['sterownik'],
    ),
    SingleLineSymbol(
      code: 'I/O',
      name: 'Moduł wejść/wyjść',
      description: 'Interfejs sygnałów cyfrowych/analogowych.',
      useCase: 'Rozproszone systemy sterowania.',
      category: 'Sterowanie i automatyka',
      graphicType: SingleLineGraphicType.automation,
      standardRef: 'PN-EN 61131',
      keywords: ['moduł io'],
    ),
    SingleLineSymbol(
      code: 'HMI',
      name: 'Panel operatorski',
      description: 'Interfejs użytkownika dla automatyki.',
      useCase: 'Pulpity i szafy sterownicze.',
      category: 'Sterowanie i automatyka',
      graphicType: SingleLineGraphicType.automation,
      standardRef: 'PN-EN 60204-1',
      keywords: ['operator panel'],
    ),
    SingleLineSymbol(
      code: 'S0',
      name: 'Przycisk STOP',
      description: 'Rozłączenie obwodu sterowania.',
      useCase: 'Panele i pulpity operatorskie.',
      category: 'Sterowanie i automatyka',
      graphicType: SingleLineGraphicType.pushButton,
      standardRef: 'PN-EN 60204-1',
      keywords: ['stop'],
    ),
    SingleLineSymbol(
      code: 'S1',
      name: 'Przycisk START',
      description: 'Załączenie obwodu sterowania.',
      useCase: 'Panele i pulpity operatorskie.',
      category: 'Sterowanie i automatyka',
      graphicType: SingleLineGraphicType.pushButton,
      standardRef: 'PN-EN 60204-1',
      keywords: ['start'],
    ),
    SingleLineSymbol(
      code: 'NO',
      name: 'Styk NO',
      description: 'Styk normalnie otwarty.',
      useCase: 'Sygnały uruchomienia i potwierdzenia.',
      category: 'Sterowanie i automatyka',
      graphicType: SingleLineGraphicType.noContact,
      standardRef: 'PN-EN 60617',
      keywords: ['normal open'],
    ),
    SingleLineSymbol(
      code: 'NC',
      name: 'Styk NC',
      description: 'Styk normalnie zamknięty.',
      useCase: 'Łańcuchy bezpieczeństwa i alarmy.',
      category: 'Sterowanie i automatyka',
      graphicType: SingleLineGraphicType.ncContact,
      standardRef: 'PN-EN 60617',
      keywords: ['normal closed'],
    ),
    SingleLineSymbol(
      code: 'H',
      name: 'Lampka sygnalizacyjna',
      description: 'Sygnalizacja stanu pracy/awarii.',
      useCase: 'Drzwi szaf i pulpity.',
      category: 'Sterowanie i automatyka',
      graphicType: SingleLineGraphicType.lamp,
      standardRef: 'PN-EN 60204-1',
      keywords: ['pilot lamp'],
    ),
    SingleLineSymbol(
      code: 'BMS',
      name: 'Interfejs BMS',
      description: 'Wymiana danych z automatyką budynku.',
      useCase: 'Monitoring energii i stanów aparatury.',
      category: 'Sterowanie i automatyka',
      graphicType: SingleLineGraphicType.automation,
      standardRef: 'BACnet/Modbus',
      keywords: ['building management'],
    ),
    SingleLineSymbol(
      code: 'KA',
      name: 'Przekaźnik pomocniczy',
      description: 'Rozszerzenie logiki i separacja obwodów sterowania.',
      useCase: 'Układy sygnałowe i zabezpieczeniowe.',
      category: 'Sterowanie i automatyka',
      graphicType: SingleLineGraphicType.contactor,
      standardRef: 'PN-EN 61810',
      keywords: ['relay'],
    ),
    SingleLineSymbol(
      code: 'KT',
      name: 'Przekaźnik czasowy',
      description: 'Opóźnione załączanie/wyłączanie obwodów.',
      useCase: 'Sekwencje technologiczne i opóźnienia.',
      category: 'Sterowanie i automatyka',
      graphicType: SingleLineGraphicType.automation,
      standardRef: 'PN-EN 61812',
      keywords: ['timer'],
    ),
    SingleLineSymbol(
      code: 'SR',
      name: 'Przekaźnik bezpieczeństwa',
      description: 'Nadzór obwodów bezpieczeństwa maszyn.',
      useCase: 'Funkcje E-STOP, osłony, kurtyny bezpieczeństwa.',
      category: 'Sterowanie i automatyka',
      graphicType: SingleLineGraphicType.automation,
      standardRef: 'PN-EN ISO 13849-1',
      keywords: ['safety relay'],
    ),

    SingleLineSymbol(
      code: 'XK',
      name: 'Linia kablowa',
      description: 'Połączenie kablowe między polami/rozdzielnicami.',
      useCase: 'Tory odpływowe i zasilające.',
      category: 'Przewody i oznaczenia',
      graphicType: SingleLineGraphicType.cable,
      standardRef: 'PN-HD 60364-5-52',
      keywords: ['kabel', 'line'],
    ),
    SingleLineSymbol(
      code: 'BB',
      name: 'Szyna zbiorcza',
      description: 'Wspólny tor rozdziału prądu.',
      useCase: 'Rozdzielnice i kanały szynowe.',
      category: 'Przewody i oznaczenia',
      graphicType: SingleLineGraphicType.busbar,
      standardRef: 'PN-EN 61439',
      keywords: ['busbar'],
    ),
    SingleLineSymbol(
      code: 'L1/L2/L3',
      name: 'Fazy zasilania',
      description: 'Oznaczenia torów fazowych.',
      useCase: 'Opis pól i odpływów trójfazowych.',
      category: 'Przewody i oznaczenia',
      graphicType: SingleLineGraphicType.phase,
      standardRef: 'PN-EN 60445',
      keywords: ['fazowy'],
    ),
    SingleLineSymbol(
      code: 'N',
      name: 'Przewód neutralny',
      description: 'Tor neutralny układu.',
      useCase: 'Obwody jednofazowe i punkty gwiazdowe.',
      category: 'Przewody i oznaczenia',
      graphicType: SingleLineGraphicType.neutral,
      standardRef: 'PN-EN 60445',
      keywords: ['neutralny'],
    ),
    SingleLineSymbol(
      code: '---',
      name: 'Linia projektowana/rezerwowa',
      description: 'Połączenie planowane lub rezerwowe.',
      useCase: 'Etapowanie inwestycji i rezerwy mocy.',
      category: 'Przewody i oznaczenia',
      graphicType: SingleLineGraphicType.lineReserved,
      standardRef: 'Praktyka projektowa',
      keywords: ['rezerwa', 'future'],
    ),
    SingleLineSymbol(
      code: 'XREF',
      name: 'Odwołanie międzyarkuszowe',
      description: 'Referencja do innego arkusza schematu.',
      useCase: 'Rozbudowane projekty wieloarkuszowe.',
      category: 'Przewody i oznaczenia',
      graphicType: SingleLineGraphicType.generic,
      standardRef: 'IEC 61082',
      keywords: ['cross reference'],
    ),
    SingleLineSymbol(
      code: 'CBL-ID',
      name: 'Oznaczenie kabla',
      description: 'Kod i parametry linii kablowej.',
      useCase: 'Spójność schemat-lista kablowa.',
      category: 'Przewody i oznaczenia',
      graphicType: SingleLineGraphicType.cable,
      standardRef: 'IEC 81346',
      keywords: ['oznaczenie', 'tag'],
    ),
    SingleLineSymbol(
      code: 'YKY',
      name: 'Kabel energetyczny YKY',
      description: 'Typ kabla miedzianego do instalacji stałych.',
      useCase: 'Trasy kablowe obwodów zasilających.',
      category: 'Przewody i oznaczenia',
      graphicType: SingleLineGraphicType.cable,
      standardRef: 'PN-EN 50525',
      keywords: ['typ kabla'],
    ),
    SingleLineSymbol(
      code: 'N2XH',
      name: 'Kabel bezhalogenowy N2XH',
      description: 'Kabel niskodymny do stref o podwyższonych wymaganiach.',
      useCase: 'Drogi ewakuacyjne i obiekty użyteczności publicznej.',
      category: 'Przewody i oznaczenia',
      graphicType: SingleLineGraphicType.cable,
      standardRef: 'PN-EN 50575 CPR',
      keywords: ['lszh', 'halogen free'],
    ),
    SingleLineSymbol(
      code: 'PH90',
      name: 'Kabel o odporności ogniowej PH90',
      description: 'Podtrzymanie funkcji w warunkach pożaru.',
      useCase: 'Obwody bezpieczeństwa ppoż.',
      category: 'Przewody i oznaczenia',
      graphicType: SingleLineGraphicType.cable,
      standardRef: 'DIN 4102-12 / PN-HD 60364-5-56',
      keywords: ['e90', 'fire resistant'],
    ),
    SingleLineSymbol(
      code: 'TRAY',
      name: 'Koryto kablowe',
      description: 'System prowadzenia tras kablowych.',
      useCase: 'Dokumentacja tras i koordynacja międzybranżowa.',
      category: 'Przewody i oznaczenia',
      graphicType: SingleLineGraphicType.lineReserved,
      standardRef: 'PN-EN 61537',
      keywords: ['trasa kablowa'],
    ),
  ];

  static List<String> categories() {
    final set = <String>{};
    for (final symbol in symbols) {
      set.add(symbol.category);
    }
    return ['Wszystkie', ...set];
  }
}
